### ISSUE TITLE
8월 30일 5회 정기모임 공덕역 오후 2시

### ISSUE THREAD

**Issue by Stupid07** [jobhope/MeetingNote#10]
- 예정일 : 2019년 8월 30일
- 장소 : 서울창업허브(마포구 백범로 31길 21) 공덕역 2번 출구 도보 10분, (구)한국산업인력공단|}
- 할일 : 전공지식 관련 정리 및 알고리즘 문제 푼것들 설명
- 논의사항: 다음주 모임 날짜에 관해서 ( 9월 3~5 예비군 및 9월 7일 코딩테스트)

**Comment by tdm1223** [comment]
@Stupid07 님 35분 지각

**Comment by Stupid07** [comment]
- [19-08-30 5회차 기록](https://github.com/jobhope/MeetingNote/blob/master/meetingNote/20190830_5.md)
