### ISSUE TITLE
8월 22일 네이버 채용 설명회 - 정자역 11시 30분 약속

### ISSUE THREAD

**Issue by tdm1223** [jobhope/MeetingNote#2]
### 참석자
@tdm1223 
@rlatjdwo555 
@Stupid07

**Comment by Stupid07** [comment]
![네이버채용설명회](https://user-images.githubusercontent.com/35564566/63503943-6fa66a00-c50b-11e9-82b7-fcd2bb7bc319.jpg)

## 컨퍼런스 후기
- [NAVER DEVELOPER OPEN CLASS 2019](https://github.com/jobhope/TechnicalNote/blob/master/NAVER_DEVELOPER_OPEN_CLASS_2019.md)
